@url=https://api.tarnamahost.ir/tag/api/Tag
@token=Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Im9DbUROU01JZW1qNWdBUUxuRWVFSXciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1OTcyMTA2NzAsImV4cCI6MTU5NzIxNDI3MCwiaXNzIjoiaHR0cHM6Ly9pZHAudGFybmFtYWhvc3QuaXIiLCJhdWQiOlsiY2F0ZWdvcnlfYXBpIiwiZmMtbWFuYWdlcl9hcGkiLCJuZXdzX2FwaSIsInBhZ2VfYXBpIiwidGFnX2FwaSIsInVwbG9hZF9hcGkiXSwiY2xpZW50X2lkIjoicGFnZV9jbGllbnRfbXZjIiwic3ViIjoiOTk4NmNjNzYtMzg1Mi00MDQxLWE1N2MtYzI0Mzc3MzBmOTcwIiwiYXV0aF90aW1lIjoxNTk2Njk3MjcwLCJpZHAiOiJsb2NhbCIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJjYXRlZ29yeV9hcGkiLCJmYy1tYW5hZ2VyX2FwaSIsIm5ld3NfYXBpIiwicGFnZV9hcGkiLCJ0YWdfYXBpIiwidXBsb2FkX2FwaSJdLCJhbXIiOlsicHdkIl19.jcFdIEuajaZWQTho_4B44Kxmn3-dESvYY63V8jzoxP-Zi8jYKzjgz9UkhzGVBy4XDdx2HVf-3HwvTw_pSLmv2YWpMPV9wjOESVbEYxeg9sTTHOnURTeTvwVB-HYY83-ifazUz8DFC4nmf6rhAtVH4lnEp-rKck0-hvORPcIVtfAacTytp3VsRQOrmb1syyTxXk78jQ29YxpM_LedP_Iw5FlKvm4OtW-mgClogiujyXv8e-D8q51hBWKZUaRklbdYRHpImmIY1L30ymJtwMu-sdBbFxtl7ZI4gwSszSTVCvezUZ9_WrNTzi7-dSNz-S23yyWWgm66VNS6cDKSsVHq6A
# SECTION Create New Tag
POST {{url}}/AddTag HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"title":"2شهر",
	"label":"تهران"
}
###

